

###
GET http://localhost:8080/article/5cfd7a39c82fd124064dcc13

###
POST http://localhost:8080/article/list
Content-Type: application/json

{    
    "limit":2
}

###
POST http://localhost:8080/article
Content-Type: application/json

{
    "title":"KK"
}
###
PUT  http://localhost:8080/article
Content-Type: application/json

{
    "_id": "5cfaed77097b44ef6bdd421b",
    "title":"AAAQQ",
    "short_description":"Bla bla bla blab alblalb alblab",
    "created_at": "2006-02-02T23:22:43-03:00"
}

###
PATCH  http://localhost:8080/article
Content-Type: application/json

{
    "_id": "5cfadccd2aee52e7e99352aa"
}

###
POST http://localhost:8080/author/list
Content-Type: application/json

{
}